### ISSUE TITLE
Add hwb() support

### ISSUE THREAD

**Issue by LeoniePhiline** [csstools/postcss-color-functional-notation#2]
Hi! :)

Could you possibly add `hwb()` support? 

The "PLUGIN" link at https://preset-env.cssdb.org/features#color-functional-notation refers here, showing a `box-shadow: 0 0 0 10px hwb(120deg 100% 25% / 80%);`, but as far as I can see, that's not actually supported by this plugin.

https://github.com/postcss/postcss-color-hwb can only be used with comma separated values, which AFAIk never were standard. (See https://github.com/postcss/postcss-color-hwb/issues/9)

Not sure which is the better place to fix this... :)

**Comment by romainmenke** [comment]
Hi @LeoniePhiline as the comma separated values syntax was never standard it would be beter if this was not handled in this plugin.

From our perspective it makes sense to add support for `hwb` -> `rgb`/`rgba`.

There is an ongoing effort to have better support for everything included in the css-color-4 spec : https://github.com/csstools/postcss-plugins/pull/70
We hope to tackle this there too.
