### ISSUE TITLE
Migrate to postcss-values-parser v3

### ISSUE THREAD

**Issue by Lucretiel** [csstools/postcss-color-functional-notation#3]
https://github.com/jonathantneal/postcss-color-functional-notation/blob/849b9606b1461c8b07972d2222020913b1872b0e/package.json#L31

postcss-values-parser v2 has some dependency warnings; please migrate to v3 to remove them.

**Comment by gknapp** [comment]
As mentioned, there's a dependency warning in package managers for this library due to a transitive  dependency on flatten 1.0.2. Displayed when installing the latest [react-scripts](https://github.com/facebook/create-react-app/tree/master/packages/react-scripts) (create-react-app):

```
warning react-scripts > postcss-preset-env > postcss-color-functional-notation > 
postcss-values-parser > flatten@1.0.2: 
I wrote this module a very long time ago; you should use something else.
```

**Comment by jonathantneal** [comment]
@gknapp, yes. I am actively working on updating all of these repositories.

https://twitter.com/jon_neal/status/1127978079652122631

**Comment by jonathantneal** [comment]
Several plugins rely on v2, and v3 took a minute to work out a few quirks, so I ended up sitting on performing the updates while I moved onto other projects (web components, phtml, actual job), and I’m now recently trying to get these updates in (as fast as possible) without breaking the rest of the plugin ecosystem. Anyone using postcss-preset-env (which is what ships in react-scripts) needs all plugins relying on this updated. Those plugins are spread across jonathantneal, csstools, and postcss orgs. I am actively working on this.

**Comment by jimblue** [comment]
Hi there!

Just a friendly ping to get some news 😄 
Any update about a new release using **postcss-values-parser v3** ?

Cheers

**Comment by jaredbeck** [comment]
FYI, I have [requested](https://github.com/shellscape/postcss-values-parser/issues/90) that `postcss-values-parser` backport (to v2) the removal of `flatten`.

EDIT: A backport is a temporary solution. The upgrade to v3 should obviously still happen.

**Comment by jimblue** [comment]
Hi @jaredbeck,
Why **postcss-value-parser** maintainer would do that?
I mean V3 of **postcss-values-parser** already have **flatten** removed.
So it makes much more sens to update to V3 in this repository!

**Comment by niftylettuce** [comment]
Will gladly donate to whoever does this

**Comment by gknapp** [comment]
Update to say `react-scripts` 3.2.0 still shows the warning on install:

```
$ npm i react-scripts@3.2.0
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
```

**Comment by jimblue** [comment]
Friendly ping @jonathantneal, can we have your input about this issue please :smile: ?! Cheers

**Comment by jonathantneal** [comment]
Thanks for your ping, @jimblue. I surely thought I would get to this after the offer from @niftylettuce, but I feel like I never have enough time lately. I have just assigned myself an hour to this at 3pm EST (-5, my current time zone). Maybe I can get this in then.

**Comment by jimblue** [comment]
Yeah I kind of know that, #busy_life... thanks for your answer :smile: 
Have a good one

**Comment by zackkrida** [comment]
Tried to look at this too, I just don't know enough about ASTs 😊 no pressure to anyone, but any offhand resources for getting into this stuff? I found it super interesting but still a bit over my head.

**Comment by Semigradsky** [comment]
Not relevant more
